create table categories (id bigint generated by default as identity, category_name varchar(255) not null unique, primary key (id));
create table transaction_types (id bigint generated by default as identity, transaction_type varchar(255) not null, primary key (id));
create table transactions (amount numeric(10,2) not null, category_id bigint not null, date timestamp(6) not null, id bigint generated by default as identity, transaction_type_id bigint not null, user_id bigint not null, description varchar(255) not null, primary key (id));
create table users (date_of_birth date not null, id bigint generated by default as identity, cpf varchar(255) not null unique, email varchar(255) not null unique, name varchar(255) not null unique, password varchar(255) not null, primary key (id));
alter table if exists transactions add constraint FKsqqi7sneo04kast0o138h19mv foreign key (category_id) references categories;
alter table if exists transactions add constraint FKohg1hygc86j35hf0ndlaxc3qy foreign key (transaction_type_id) references transaction_types;
alter table if exists transactions add constraint FKqwv7rmvc8va8rep7piikrojds foreign key (user_id) references users;
