create table tb_account (date_of_birth date not null, id bigint generated by default as identity, bank varchar(255) not null, cpf varchar(255) not null, name varchar(255) not null, primary key (id));
